### ISSUE TITLE
In-Place Extractions going to /config directory.

### ISSUE THREAD

**Issue by tompapajr** [d8ahazard/deluge-extractor#10]
I've been using the extractor (SimpleExtractor-1.3-py3.8.egg
) within a docker container (binhex-dockervpn). They file structure layout is like this:

/data/downloads/completed/example_torrent/file.rar,file.r01 . etc
/config/ - here are the deluge plug-ins, configs, logs etc.

simpleextractor.conf
{
    "file": 1,
    "format": 1
}{
    "extract_in_place": true,
    "extract_path": "",
    "extract_selected_folder": false,
    "extract_torrent_root": false,
    "label_filter": ""
}

I have configured "In-Place" in the Extractor settings (not using tags). Left the Extraction path blank.
**Extracted files end up in /config/example_torrent/ instead of in-place @ /data/downloads/completed/example_torrent/**

**Comment by paulmorabito** [comment]
I believe I have the same same problem. My config is identical however, I am getting 

```
EXTRACTOR: Error creating destination folder: [Errno 13] Permission denied: 'Linux-ISO'
```

With Linux-ISO being the name of the torrent and with the same directory existing in my real downloads location and containing the rar files.

I'm using the latest version of the linuxserver deluge docker image and v1.3 of this plugin.
