### ISSUE TITLE
Could this work with unrar on linux?

### ISSUE THREAD

**Issue by BinsonBuzz** [d8ahazard/deluge-extractor#2]
I'm desperate!

Thanks in advance

**Comment by danpowell88** [comment]
Yes

**Comment by BinsonBuzz** [comment]
thanks.  I should have been a bit clearer I think.  I was asking if it could be made to support unrar on linux as when I tried to install it didn't work as I think it failed the 7-zip test

**Comment by danpowell88** [comment]
I'm using it in a docker container that only contains unrar, however it does also contain unzip

https://github.com/binhex/arch-deluge

**Comment by BinsonBuzz** [comment]
Yeah I was being stupid - got it working.  Sorry
