### ISSUE TITLE
Few bug fixes

### ISSUE THREAD

**Issue by mikepauer** [d8ahazard/deluge-extractor#4]
Testing this out, I came across a couple bugs/issues, so thought i'd provide the fixes I found.

All are in core.py

Spacing on 'tid.is_finished = false' is off causing files to only get unlocked if they had extraction happen. Reducing justification to 8 spaces so it's outside the if statement fixes that.

In label processing you are using self.config['extract_labels'] instead of self.config['label_filters'] causing app to crash. Fix is to replace all extract_labels with label_filters

in same section, you have 2 forloops running both using label which causes matching even when there isn't a match. Fix is to change 'for label in label_list:' to 'for singlelabel in label_list:' and just below it 'if label.strip() == label:' to 'if singlelabel.strip() == label:

**Comment by d8ahazard** [comment]
Fixed with 1.2 release.
