### ISSUE TITLE
In-Place extraction failing when valid file found to extract

### ISSUE THREAD

**Issue by ghost** [d8ahazard/deluge-extractor#6]
Settings are set for "in-place" with a destination directory specified (should be ignored by in-place), using version 1.1 of python 3.8 egg. It looks like it's unable to find the "download_location" value when trying to extract in-place.

19:29:51 [INFO ][deluge_simpleextractor.core :238 ] We have a Label config
19:29:51 [INFO ][deluge_simpleextractor.core :241 ] Data from Label plugin: radarr
19:29:51 [INFO ][deluge_simpleextractor.core :246 ] We have a label plus config
19:29:51 [INFO ][deluge_simpleextractor.core :128 ] Schmancy label collector: ['radarr']
19:29:51 [INFO ][deluge_simpleextractor.core :158 ] No label, extracting.
19:29:51 [INFO ][deluge_simpleextractor.core :168 ] Handling file Movie/Proof/Movie.proof.jpg
19:29:51 [INFO ][deluge_simpleextractor.core :174 ] Cannot extract file with unknown file type: Movie/Proof/Movie.proof.jpg
19:29:51 [INFO ][deluge_simpleextractor.core :168 ] Handling file Movie/Subs/Movie.subs.rar
19:29:51 [ERROR ][deluge.core.eventmanager :43 ] Event handler TorrentFinishedEvent failed in <bound method Core._on_torrent_finished of <deluge_simpleextractor.core.Core object at 0x7f4530bb4780>> with exception 'download_location'

**Comment by d8ahazard** [comment]
Fixed with #B5C96D4.
